# DataTypes & Attributes

In [1]:
import numpy as np

In [16]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [17]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],

              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [18]:
a1.shape

(3,)

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [19]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [21]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
#Create a DataFrame from a NumPy Array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Array

In [24]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int32')

In [27]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [29]:
type(ones)

numpy.ndarray

In [31]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# range antara 0 - 10 dg kelipatan 2
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 5, 2, 4, 8],
       [2, 4, 1, 3, 8],
       [2, 9, 1, 7, 8]])

In [36]:
random_array.size

15

In [37]:
random_array.shape

(3, 5)

In [38]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.54333726, 0.94920867, 0.27397231],
       [0.00843853, 0.80148635, 0.61320799],
       [0.96803274, 0.08920844, 0.26091109],
       [0.93789076, 0.43985677, 0.72988636],
       [0.68525157, 0.7739094 , 0.3687289 ]])

In [50]:
#Pseudo-random numbers

#kalo ga pake seed, output bakal beda terus tiap di run
#pake seed, hasilnya bakal tetep

np.random.seed(seed=15)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[8, 5, 5],
       [7, 0, 7],
       [5, 6, 1],
       [7, 0, 4],
       [9, 7, 5]])

# Viewing Arrays & Matrices

In [51]:
np.unique(random_array_4)

array([0, 1, 4, 5, 6, 7, 8, 9])

In [52]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 6, 8, 2, 1],
         [1, 0, 5, 2, 2],
         [1, 8, 5, 6, 9],
         [2, 8, 6, 8, 8]],

        [[3, 4, 7, 2, 0],
         [5, 7, 3, 8, 5],
         [3, 1, 0, 8, 7],
         [5, 8, 1, 2, 8]],

        [[3, 1, 3, 7, 2],
         [7, 2, 0, 0, 7],
         [6, 4, 4, 3, 7],
         [5, 6, 0, 9, 0]]],


       [[[4, 8, 6, 3, 2],
         [7, 4, 2, 2, 9],
         [3, 3, 4, 3, 5],
         [3, 0, 0, 6, 1]],

        [[2, 2, 1, 4, 7],
         [8, 7, 2, 5, 3],
         [8, 9, 4, 9, 4],
         [4, 1, 0, 4, 7]],

        [[8, 5, 9, 3, 0],
         [4, 0, 1, 9, 4],
         [5, 4, 8, 3, 9],
         [1, 3, 5, 1, 6]]]])

In [53]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
#Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[3],
         [1],
         [1],
         [2]],

        [[3],
         [5],
         [3],
         [5]],

        [[3],
         [7],
         [6],
         [5]]],


       [[[4],
         [7],
         [3],
         [3]],

        [[2],
         [8],
         [8],
         [4]],

        [[8],
         [4],
         [5],
         [1]]]])

# Manipulating & Compareting Arrays

Arithmetic

In [56]:
a1

array([1, 2, 3])

In [57]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [58]:
a1 + ones

array([2., 3., 4.])

In [59]:
a1 - ones

array([0., 1., 2.])

In [60]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [ ]:
# Cara reshape a2 biar kek a3 (cari sendiri anjir)
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [64]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [66]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [67]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [68]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])